// Zentraler Bundesland-Katalog für Landing-Pages /aerzte/bundesland/[slug].
// stateNames enthält die Werte, die im Feld `state` der doctor_places-Collection
// stehen können (Google gibt teils "Bayern", teils "Freistaat Bayern" zurück).
// topCities enthält die redaktionell wichtigsten Städte pro Bundesland – diese
// werden verlinkt, unabhängig davon, ob wir Praxen dort in der DB haben.

export const BUNDESLAENDER = [
  {
    slug: 'baden-wuerttemberg',
    label: 'Baden-Württemberg',
    dativ: 'in Baden-Württemberg',
    capital: 'Stuttgart',
    stateNames: ['Baden-Württemberg'],
    topCities: [
      { name: 'Stuttgart', slug: 'stuttgart' },
      { name: 'Karlsruhe', slug: 'karlsruhe' },
      { name: 'Mannheim', slug: 'mannheim' },
      { name: 'Freiburg', slug: 'freiburg' },
      { name: 'Heidelberg', slug: 'heidelberg' },
      { name: 'Heilbronn', slug: 'heilbronn' },
      { name: 'Ulm', slug: 'ulm' },
      { name: 'Pforzheim', slug: 'pforzheim' },
      { name: 'Reutlingen', slug: 'reutlingen' },
      { name: 'Tübingen', slug: 'tuebingen' },
    ],
    intro: 'Baden-Württemberg ist mit rund 11 Millionen Einwohnern das drittgrößte Bundesland Deutschlands. Es verfügt über eine dichte medizinische Infrastruktur mit renommierten Universitätskliniken in Heidelberg, Tübingen, Freiburg und Ulm sowie zahlreichen Fachärzten und Hausarztpraxen in Ballungsräumen wie Stuttgart, Mannheim und Karlsruhe.',
  },
  {
    slug: 'bayern',
    label: 'Bayern',
    dativ: 'in Bayern',
    capital: 'München',
    stateNames: ['Bayern', 'Freistaat Bayern'],
    topCities: [
      { name: 'München', slug: 'muenchen' },
      { name: 'Nürnberg', slug: 'nuernberg' },
      { name: 'Augsburg', slug: 'augsburg' },
      { name: 'Regensburg', slug: 'regensburg' },
      { name: 'Würzburg', slug: 'wuerzburg' },
      { name: 'Ingolstadt', slug: 'ingolstadt' },
      { name: 'Fürth', slug: 'fuerth' },
      { name: 'Erlangen', slug: 'erlangen' },
      { name: 'Bayreuth', slug: 'bayreuth' },
      { name: 'Bamberg', slug: 'bamberg' },
    ],
    intro: 'Bayern ist mit rund 13 Millionen Einwohnern das zweitgrößte und flächenmäßig größte Bundesland Deutschlands. Die medizinische Versorgung ist besonders im Großraum München, Nürnberg und Erlangen sehr dicht, mit führenden Universitätskliniken (LMU München, TU München, Universitätsklinikum Erlangen) und einem starken Netz an niederögelassenen Fachärzten.',
  },
  {
    slug: 'berlin',
    label: 'Berlin',
    dativ: 'in Berlin',
    capital: 'Berlin',
    stateNames: ['Berlin'],
    topCities: [
      { name: 'Berlin', slug: 'berlin' },
    ],
    intro: 'Berlin ist als Stadtstaat und Bundeshauptstadt mit über 3,7 Millionen Einwohnern die größte Stadt Deutschlands. Die medizinische Versorgung ist überdurchschnittlich dicht: Charité, Vivantes-Kliniken und tausende niederögelassene Ärzte in allen zwölf Bezirken.',
  },
  {
    slug: 'brandenburg',
    label: 'Brandenburg',
    dativ: 'in Brandenburg',
    capital: 'Potsdam',
    stateNames: ['Brandenburg'],
    topCities: [
      { name: 'Potsdam', slug: 'potsdam' },
      { name: 'Cottbus', slug: 'cottbus' },
      { name: 'Brandenburg an der Havel', slug: 'brandenburg-an-der-havel' },
      { name: 'Frankfurt (Oder)', slug: 'frankfurt-oder' },
      { name: 'Oranienburg', slug: 'oranienburg' },
    ],
    intro: 'Brandenburg umgibt die Hauptstadt Berlin und ist mit rund 2,5 Millionen Einwohnern überwiegend ländlich geprägt. Die medizinische Versorgung konzentriert sich auf Potsdam, Cottbus sowie das sogenannte Berliner Umland; Zugang zu Fachärzten der Berliner Kliniken ist für viele Brandenburger üblich.',
  },
  {
    slug: 'bremen',
    label: 'Bremen',
    dativ: 'in Bremen',
    capital: 'Bremen',
    stateNames: ['Bremen', 'Freie Hansestadt Bremen'],
    topCities: [
      { name: 'Bremen', slug: 'bremen' },
      { name: 'Bremerhaven', slug: 'bremerhaven' },
    ],
    intro: 'Die Freie Hansestadt Bremen ist mit rund 680.000 Einwohnern der kleinste Stadtstaat Deutschlands. Das Klinikum Bremen-Mitte, Klinikum Links der Weser und das Klinikum Bremen-Nord bieten überregionale Versorgung; zusätzlich gibt es ein dichtes Netz niederögelassener Ärzte in beiden Stadtteilen (Bremen-Stadt und Bremerhaven).',
  },
  {
    slug: 'hamburg',
    label: 'Hamburg',
    dativ: 'in Hamburg',
    capital: 'Hamburg',
    stateNames: ['Hamburg', 'Freie und Hansestadt Hamburg'],
    topCities: [
      { name: 'Hamburg', slug: 'hamburg' },
    ],
    intro: 'Hamburg ist als Stadtstaat mit rund 1,9 Millionen Einwohnern die zweitgrößte Stadt Deutschlands. Die medizinische Versorgung ist überdurchschnittlich – mit dem Universitätsklinikum Hamburg-Eppendorf (UKE) als Zentrum sowie zahlreichen Fachärzten in den sieben Bezirken.',
  },
  {
    slug: 'hessen',
    label: 'Hessen',
    dativ: 'in Hessen',
    capital: 'Wiesbaden',
    stateNames: ['Hessen'],
    topCities: [
      { name: 'Frankfurt am Main', slug: 'frankfurt-am-main' },
      { name: 'Wiesbaden', slug: 'wiesbaden' },
      { name: 'Kassel', slug: 'kassel' },
      { name: 'Darmstadt', slug: 'darmstadt' },
      { name: 'Offenbach', slug: 'offenbach' },
      { name: 'Hanau', slug: 'hanau' },
      { name: 'Marburg', slug: 'marburg' },
      { name: 'Gießen', slug: 'giessen' },
    ],
    intro: 'Hessen ist mit rund 6,3 Millionen Einwohnern eines der wirtschaftsstärksten Bundesländer. Der Ballungsraum Rhein-Main um Frankfurt bildet den medizinischen Schwerpunkt, mit Universitätskliniken in Frankfurt, Marburg und Gießen sowie einer sehr dichten Facharzt-Versorgung.',
  },
  {
    slug: 'mecklenburg-vorpommern',
    label: 'Mecklenburg-Vorpommern',
    dativ: 'in Mecklenburg-Vorpommern',
    capital: 'Schwerin',
    stateNames: ['Mecklenburg-Vorpommern'],
    topCities: [
      { name: 'Rostock', slug: 'rostock' },
      { name: 'Schwerin', slug: 'schwerin' },
      { name: 'Neubrandenburg', slug: 'neubrandenburg' },
      { name: 'Stralsund', slug: 'stralsund' },
      { name: 'Greifswald', slug: 'greifswald' },
      { name: 'Wismar', slug: 'wismar' },
    ],
    intro: 'Mecklenburg-Vorpommern ist mit rund 1,6 Millionen Einwohnern das am dünnsten besiedelte Flächenland Deutschlands. Die medizinische Versorgung konzentriert sich auf Rostock (Universitätsmedizin), Greifswald (Universitätsmedizin) und Schwerin; in ländlichen Regionen sind Facharzt-Wege oft länger.',
  },
  {
    slug: 'niedersachsen',
    label: 'Niedersachsen',
    dativ: 'in Niedersachsen',
    capital: 'Hannover',
    stateNames: ['Niedersachsen'],
    topCities: [
      { name: 'Hannover', slug: 'hannover' },
      { name: 'Braunschweig', slug: 'braunschweig' },
      { name: 'Oldenburg', slug: 'oldenburg' },
      { name: 'Osnabrück', slug: 'osnabrueck' },
      { name: 'Wolfsburg', slug: 'wolfsburg' },
      { name: 'Göttingen', slug: 'goettingen' },
      { name: 'Salzgitter', slug: 'salzgitter' },
      { name: 'Hildesheim', slug: 'hildesheim' },
    ],
    intro: 'Niedersachsen ist flächenmäßig das zweitgrößte Bundesland und hat rund 8 Millionen Einwohner. Die medizinische Landschaft reicht von der Medizinischen Hochschule Hannover (MHH) und der Universitätsmedizin Göttingen bis zu einem breiten Netz niederögelassener Ärzte in den Städten und im ländlichen Raum.',
  },
  {
    slug: 'nordrhein-westfalen',
    label: 'Nordrhein-Westfalen',
    dativ: 'in Nordrhein-Westfalen',
    capital: 'Düsseldorf',
    stateNames: ['Nordrhein-Westfalen'],
    topCities: [
      { name: 'Köln', slug: 'koeln' },
      { name: 'Düsseldorf', slug: 'duesseldorf' },
      { name: 'Dortmund', slug: 'dortmund' },
      { name: 'Essen', slug: 'essen' },
      { name: 'Duisburg', slug: 'duisburg' },
      { name: 'Bochum', slug: 'bochum' },
      { name: 'Wuppertal', slug: 'wuppertal' },
      { name: 'Bielefeld', slug: 'bielefeld' },
      { name: 'Bonn', slug: 'bonn' },
      { name: 'Münster', slug: 'muenster' },
      { name: 'Aachen', slug: 'aachen' },
      { name: 'Mönchengladbach', slug: 'moenchengladbach' },
    ],
    intro: 'Nordrhein-Westfalen ist mit rund 18 Millionen Einwohnern das bevölkerungsreichste Bundesland Deutschlands. Der medizinische Ballungsraum Rhein-Ruhr bietet mit den Universitätskliniken Köln, Düsseldorf, Aachen, Bonn, Essen und Münster eine der dichtesten Versorgungslandschaften Europas.',
  },
  {
    slug: 'rheinland-pfalz',
    label: 'Rheinland-Pfalz',
    dativ: 'in Rheinland-Pfalz',
    capital: 'Mainz',
    stateNames: ['Rheinland-Pfalz'],
    topCities: [
      { name: 'Mainz', slug: 'mainz' },
      { name: 'Ludwigshafen', slug: 'ludwigshafen' },
      { name: 'Koblenz', slug: 'koblenz' },
      { name: 'Trier', slug: 'trier' },
      { name: 'Kaiserslautern', slug: 'kaiserslautern' },
      { name: 'Worms', slug: 'worms' },
    ],
    intro: 'Rheinland-Pfalz hat rund 4,1 Millionen Einwohner. Die medizinische Versorgung ist stark durch die Universitätsmedizin Mainz und die Ballungsräume Ludwigshafen/Mannheim, Trier und Koblenz geprägt.',
  },
  {
    slug: 'saarland',
    label: 'Saarland',
    dativ: 'im Saarland',
    capital: 'Saarbrücken',
    stateNames: ['Saarland'],
    topCities: [
      { name: 'Saarbrücken', slug: 'saarbruecken' },
      { name: 'Neunkirchen', slug: 'neunkirchen' },
      { name: 'Homburg', slug: 'homburg' },
      { name: 'Völklingen', slug: 'voelklingen' },
    ],
    intro: 'Das Saarland ist mit rund 990.000 Einwohnern das kleinste Flächenland Deutschlands. Die medizinische Versorgung konzentriert sich auf den Ballungsraum Saarbrücken sowie das Universitätsklinikum in Homburg.',
  },
  {
    slug: 'sachsen',
    label: 'Sachsen',
    dativ: 'in Sachsen',
    capital: 'Dresden',
    stateNames: ['Sachsen', 'Freistaat Sachsen'],
    topCities: [
      { name: 'Leipzig', slug: 'leipzig' },
      { name: 'Dresden', slug: 'dresden' },
      { name: 'Chemnitz', slug: 'chemnitz' },
      { name: 'Zwickau', slug: 'zwickau' },
      { name: 'Plauen', slug: 'plauen' },
      { name: 'Görlitz', slug: 'goerlitz' },
    ],
    intro: 'Sachsen hat rund 4 Millionen Einwohner und eine besonders starke medizinische Infrastruktur mit den Universitätskliniken Leipzig und Dresden. Fachärzte und Hausarzt-Praxen sind in Leipzig, Dresden und Chemnitz sehr dicht vorhanden.',
  },
  {
    slug: 'sachsen-anhalt',
    label: 'Sachsen-Anhalt',
    dativ: 'in Sachsen-Anhalt',
    capital: 'Magdeburg',
    stateNames: ['Sachsen-Anhalt'],
    topCities: [
      { name: 'Halle (Saale)', slug: 'halle-saale' },
      { name: 'Magdeburg', slug: 'magdeburg' },
      { name: 'Dessau-Roßlau', slug: 'dessau-rosslau' },
      { name: 'Wittenberg', slug: 'wittenberg' },
    ],
    intro: 'Sachsen-Anhalt hat rund 2,2 Millionen Einwohner. Universitätskliniken in Magdeburg und Halle (Saale) bilden das Rückgrat der Facharzt-Versorgung.',
  },
  {
    slug: 'schleswig-holstein',
    label: 'Schleswig-Holstein',
    dativ: 'in Schleswig-Holstein',
    capital: 'Kiel',
    stateNames: ['Schleswig-Holstein'],
    topCities: [
      { name: 'Kiel', slug: 'kiel' },
      { name: 'Lübeck', slug: 'luebeck' },
      { name: 'Flensburg', slug: 'flensburg' },
      { name: 'Neumünster', slug: 'neumuenster' },
      { name: 'Norderstedt', slug: 'norderstedt' },
    ],
    intro: 'Schleswig-Holstein hat rund 2,9 Millionen Einwohner. Das Universitätsklinikum Schleswig-Holstein (UKSH) mit Standorten in Kiel und Lübeck zählt zu den größten Kliniken Deutschlands.',
  },
  {
    slug: 'thueringen',
    label: 'Thüringen',
    dativ: 'in Thüringen',
    capital: 'Erfurt',
    stateNames: ['Thüringen', 'Freistaat Thüringen'],
    topCities: [
      { name: 'Erfurt', slug: 'erfurt' },
      { name: 'Jena', slug: 'jena' },
      { name: 'Gera', slug: 'gera' },
      { name: 'Weimar', slug: 'weimar' },
      { name: 'Eisenach', slug: 'eisenach' },
    ],
    intro: 'Thüringen hat rund 2,1 Millionen Einwohner. Das Universitätsklinikum Jena ist das medizinische Zentrum, dazu kommen Städte wie Erfurt und Gera mit dichter Facharzt-Struktur.',
  },
];

export function bundeslandBySlug(slug) {
  return BUNDESLAENDER.find((b) => b.slug === slug) || null;
}
